# Generated by Django 4.0.3 on 2022-03-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('nama', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat', models.CharField(blank=True, max_length=100, null=True)),
                ('npm', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('photo', models.FileField(null=True, upload_to='mahasiswa/media/images')),
            ],
        ),
    ]
